# Numpy (Numerical Python) Notları

Temelinde tek boyutlu ve matrisler olan bunlarla yapılabilecek işlemleri, bilimsel hesaplamaları kolaylaştıran bir python modülüdür.

## İçerik

1. [Modül Kütüphanesini Import Etme](#1)
2. [Dizi Yaratmak](#2)
3. [Denetim Özellikleri](#3)
4. [Copying Sorting Reshaping](#4)
5. [Adding Removing](#5)
6. [Combining Splitting](#6)
7. [Indexing Slicing Subsetting](#7)
8. [Scaler Math](#8)
9. [Vector Math](#9)
10. [İstatistik](#10)

<a id='1'></a><br>
## Modül Kütüphanesini Import Etme

Numpy Kütüphanesini;

- conda install numpy (conda kullananlar)

- pip install numpy (pip kullananlar)

şeklinde kurabilir. 

Bir kütüphane ile çalışırken karşılaşılan hatalardan biri yazdığınız kod parçacığı ile kütüphanin sürümlerinin uymamasıdır. O yüzden versiyon kontrolü yapmak önemlidir.

In [1]:
import numpy as np  # kütüphane import edildi

In [2]:
np.version.version

'1.18.1'

<a id='2'></a><br>
## Dizi yaratmak

Numpy hızlı bir biçimde vektörler ve matrisler oluşturur ve kullanımlarını kolaylaştırır. 

In [3]:
vector = np.array([1,2,3,4,5])
vector

array([1, 2, 3, 4, 5])

'vector' değişkeninin tipini kontrol ettiğimizde:

In [5]:
type(vector)

numpy.ndarray

Eğer dizinin belirli bir aralıkta olması istenirse (örnekte 1'den 20'ye kadar ikişer ikişer, 20 dahil değil)

In [6]:
vector2 = np.arange(1,20,2)
vector2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Aşağıdaki örnekte ise 10'dan 50'ye 20 tane sayı üretir.

In [7]:
vectorLin = np.linspace(10,50,20)
vectorLin

array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ])

In [12]:
vector3 = np.arange(1,16) # arange fonksiyonunda spesifik bir artış istenmiyorsa 
vector3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

'vector' ve 'vector2' tek boyutlu (1xn)'lik vektörledir. Eğer iki boyutlu(matris) istenirse:

In [10]:
two_dimension = np.array([[1,2,3,4,5,6,7,8,9,10],
                         [11,12,13,14,15,16,17,18,19,20]])
two_dimension

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

Kullanılacak olan matrisin tamamen 0'lardan oluşması istenirse:

In [14]:
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Matristeki bir değere atama işlemi :

In [15]:
zero[2,2] = 5
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 5., 0.]])

Dolayısıyla bir değişken seçme işleminide öğrenmiş olduk (zero[2,2]) 

In [18]:
vector

array([1, 2, 3, 4, 5])

In [19]:
vector[2] # burada da diziden bir seçme işlemi yapmış olduk. Diziler 0. indisten başlar.

3

Devam edelim; Kullanılacak olan matrisin tamamı 1'lerden oluşmasını istenirse:

In [20]:
one = np.ones((3,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Boş bir matris:

In [21]:
empty = np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

nxn'lik bir diagonal matris (diagonal: Doğrusal cebirde köşegen matris, ilkköşegenin dışında kalan girişlerin tümü sıfır ve genellikle kare matris olan bir matrisdir. -_vikipedi_): 

In [22]:
arrayEye =np.eye(5)
arrayEye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Bütün bir matrisi tek bir sayı ile doldurulması (örnekte 2x3'lük bir matris 8 sayısı ile doldurulmuş):

In [23]:
arrayFull = np.full((2,3),8)
arrayFull

array([[8, 8, 8],
       [8, 8, 8]])

Matrisi random float sayılardan oluşturma

In [24]:
vector4 = np.random.rand(4,5)
vector4

array([[0.21742871, 0.80268968, 0.22559868, 0.583517  , 0.5523403 ],
       [0.89772702, 0.69633127, 0.21906737, 0.29241278, 0.44865392],
       [0.2505541 , 0.81597956, 0.82764579, 0.60787041, 0.32741786],
       [0.86654241, 0.70192253, 0.89186035, 0.02733217, 0.87641427]])

Bu arada herhangi bir fonksiyonun parametreleri ve alt fonksiyonlarına ulaşmak için ? kullanılır

In [25]:
?np.random

Type:        module
String form: <module 'numpy.random' from 'C:\\Users\\HP\\anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>
File:        c:\users\hp\anaconda3\lib\site-packages\numpy\random\__init__.py
Docstring:  
Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a BitGenerat

'np.random.normal', tek bir float sayı üretir.

In [27]:
vector_normal_random = np.random.normal()
vector_normal_random

-0.6487379844652181

In [28]:
vector_normal_random_size = np.random.normal(size=4)
vector_normal_random_size

array([ 1.2357465 , -0.57829477, -1.09596176,  1.96619263])

In [29]:
type(vector_normal_random_size)

numpy.ndarray

In [31]:
vector_rand = np.random.randint(low=0,high=100,size=1) # 0dan 100'e 1 tane int sayı üret
vector_rand 

array([75])

<a id='3'></a><br>
## Denetim Özellikleri

In [33]:
vector2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

'vector2' size :

In [32]:
vector2.size

10

'vector2' boyutu(row,column): 

In [34]:
vector.shape

(5,)

(5,) : 5x1 anlamına gelir

Veri tipi: 

In [37]:
vector2.dtype.name

'int32'

Diziyi listeye çevirme:

In [41]:
vec2_list = vector2.tolist()
vec2_list

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [43]:
type(vec2_list)

list

Bilgi edinmek için:

In [44]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

<a id='4'></a><br>
## Copying Sorting Reshaping

Bazen veriler ile çalışırken geri dönüşünü olmayan zararlar verilebilir. Kopyalama ile orijinal veriyi korumak için ideal bir yöntemdir. 

In [45]:
new_array = np.arange(1,21)
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
array_copy = np.copy(new_array)
array_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Dizide belirli bir veri tipini gösterme:

In [47]:
array_copy.view(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Dizide sıralama:

In [48]:
np.sort(new_array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [49]:
?np.sort

Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecif

kind = quicksort/mergesort/heapsort/timsort seçenekleri

In [50]:
np.sort(new_array,kind="quicksort")

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrisleri diziye dönüştürme:

In [51]:
two_dimension = np.array([[1,2,3,4,5,6,7,8,9,10],
                         [11,12,13,14,15,16,17,18,19,20]])
two_dimension

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [52]:
two_dimension.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Bir matrisin transpozunu alma: 

In [54]:
two_dimension.T

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])

bir dizinin şeklini değiştirme:

In [55]:
vector3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
vector3.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

<a id='5'></a><br>
## Adding Removing

In [57]:
arr = np.arange(2,6)
arr

array([2, 3, 4, 5])

Diziye yeni bir sayı ekleme:

In [58]:
np.append(arr,6)

array([2, 3, 4, 5, 6])

Dizide belirli indekse sayı ekleme:

In [59]:
np.insert(arr,2,7)

array([2, 3, 7, 4, 5])

Dizide belirli bir indeksteki sayıyı silme:

In [60]:
np.delete(arr,3,axis=0)

array([2, 3, 4])

<a id='6'></a><br>
## Combining Splitting

In [62]:
arr = np.arange(1,3)
arr

array([1, 2])

In [63]:
arr2 = np.arange(4,9)
arr2

array([4, 5, 6, 7, 8])

İki diziyi birleştirme:

In [64]:
con = np.concatenate((arr,arr2),axis=0)
con

array([1, 2, 4, 5, 6, 7, 8])

Diziyi belirli bir sayıda bölme:

In [74]:
np.split(arr,2)

[array([1]), array([2])]

In [75]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

<a id='7'></a><br>
## Indexing Slicing Subsetting

In [77]:
arr2

array([4, 5, 6, 7, 8])

Belirli indeksteki sayıyı geri döndürme:

In [78]:
arr2[3]

7

In [79]:
two_dimension

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

Matristen herhangi bir indeksten sayı geri döndürme:

In [80]:
two_dimension[1,4]

15

Belirli bir indekse sayı atama:

In [82]:
arr2[2] = 10
arr2

array([ 4,  5, 10,  7,  8])

In [83]:
two_dimension[1,5] = 21
two_dimension

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 21, 17, 18, 19, 20]])

Dizideki belirli bir sayı kümesine alma:

In [84]:
q_arr = np.arange(1,9)
q_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
q_arr[1:4] # 1.indeksten 4.indeksi seç

array([2, 3, 4])

In [88]:
q_arr[:3] # ilk üçü seç

array([1, 2, 3])

In [90]:
q_arr[3:] # 3.indeks dahil geri kalanı seç

array([4, 5, 6, 7, 8])

In [91]:
two_dimension[1:3,1] 

array([12])

In [98]:
two_dimension[:,2]

array([ 3, 13])

In [100]:
two_dimension[:1,2]

array([3])

In [99]:
two_dimension[:,2]

array([ 3, 13])

In [101]:
q_arr<5

array([ True,  True,  True,  True, False, False, False, False])

In [102]:
(q_arr<3) & (q_arr>5)

array([False, False, False, False, False, False, False, False])

In [103]:
~q_arr

array([-2, -3, -4, -5, -6, -7, -8, -9], dtype=int32)

In [104]:
q_arr[q_arr<6]

array([1, 2, 3, 4, 5])

<a id='8'></a><br>
## Scaler Math

In [105]:
np.add(q_arr,1)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.subtract(q_arr,3)

array([-2, -1,  0,  1,  2,  3,  4,  5])

In [107]:
np.multiply(q_arr,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [108]:
np.divide(q_arr,4)

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [109]:
np.power(q_arr,5)

array([    1,    32,   243,  1024,  3125,  7776, 16807, 32768],
      dtype=int32)

<a id='9'></a><br>
## Vector Math

In [110]:
np.array_equal(arr,arr2)

False

In [111]:
np.sqrt(arr2)

array([2.        , 2.23606798, 3.16227766, 2.64575131, 2.82842712])

In [112]:
np.sin(arr2)

array([-0.7568025 , -0.95892427, -0.54402111,  0.6569866 ,  0.98935825])

In [113]:
np.log(arr2)

array([1.38629436, 1.60943791, 2.30258509, 1.94591015, 2.07944154])

In [114]:
np.abs(arr2)

array([ 4,  5, 10,  7,  8])

In [115]:
np.ceil(arr2)

array([ 4.,  5., 10.,  7.,  8.])

In [116]:
np.floor(arr2)

array([ 4.,  5., 10.,  7.,  8.])

In [117]:
np.round(arr2)

array([ 4,  5, 10,  7,  8])

<a id='10'></a><br>
## İstatistik

Dizideki sayıların ortalama alma:

In [118]:
np.mean(arr2,axis=0)

6.8

Dizideki sayıların toplamını bulma:

In [119]:
np.sum(arr2)

34

Dizinin içerisindeki en büyük sayıyı bulma:

In [121]:
np.max(arr2)

10

Dizinin içerindeki en küçük sayıyı bulma:

In [122]:
np.min(arr2)

4

Dizinin sayılarının varyansını bulma:

In [123]:
np.var(arr2)

4.5600000000000005

Dizinin belirli bir eksende standart sapmasını bulur:

In [124]:
np.std(arr,axis=0)

1.707825127659933